# -*- coding: utf-8 -*-
"""
/***************************************************************************
 quickign
                                 A QGIS plugin
 QuickIGN
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-02-10
        git sha              : $Format:%H$
        copyright            : (C) 2021 by Chloe Morgat
        email                : chloe.morgat@ensg.eu
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
from qgis.core import QgsRasterLayer, QgsProject, QgsVectorLayer
from qgis.utils import iface


from PyQt5.QtGui import QColor, QFont
from qgis.core import QgsFillSymbol, QgsSingleSymbolRenderer, QgsLineSymbol
from qgis.core import QgsTextFormat, QgsTextBufferSettings, QgsVectorLayerSimpleLabeling
from qgis.core import QgsPalLayerSettings
from qgis.core import QgsMarkerSymbol

# Initialize Qt resources from file resources.py
from .resources import *


# Import the code for the DockWidget
from .QuickIGN_dockwidget import QuickIGNDockWidget
import os.path


class QuickIGN:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        self.canvas= iface.mapCanvas()

        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)

        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'QuickIGN_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&QuickIGN')
        # TODO: We are going to let the user set this up in a future iteration
        self.toolbar = self.iface.addToolBar(u'QuickIGN')
        self.toolbar.setObjectName(u'QuickIGN')

        #print "** INITIALIZING QuickIGN"

        self.pluginIsActive = False
        self.dockwidget = None


    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('QuickIGN', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action


    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/quickign/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'QuickIGN'),
            callback=self.run,
            parent=self.iface.mainWindow())

    #--------------------------------------------------------------------------

    def onClosePlugin(self):
        """Cleanup necessary items here when plugin dockwidget is closed"""

        #print "** CLOSING QuickIGN"

        # disconnects
        self.dockwidget.closingPlugin.disconnect(self.onClosePlugin)

        # remove this statement if dockwidget is to remain
        # for reuse if plugin is reopened
        # Commented next statement since it causes QGIS crashe
        # when closing the docked window:
        # self.dockwidget = None

        self.pluginIsActive = False


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""

        #print "** UNLOAD QuickIGN"

        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&QuickIGN'),
                action)
            self.iface.removeToolBarIcon(action)
        # remove the toolbar
        del self.toolbar

    #--------------------------------------------------------------------------

    def run(self):
        """Run method that loads and starts the plugin"""

        if not self.pluginIsActive:
            self.pluginIsActive = True

            #print "** STARTING QuickIGN"

            # dockwidget may not exist if:
            #    first run of plugin
            #    removed on close (see self.onClosePlugin method)
            if self.dockwidget == None:
                # Create the dockwidget (after translation) and keep reference
                self.dockwidget = QuickIGNDockWidget()
                
            # Mise en page de l'interface du Plugin :
            self.dockwidget.pushButton.setStyleSheet("color : #6CE152")
            
            #Connection des flux accéssible par l'IGN aux checkbox : 
            self.dockwidget.Boxphoto.clicked.connect(self.affichePhotoAerienne)
            self.dockwidget.Boxplani.clicked.connect(self.affichePlaniIGN)
            self.dockwidget.Boxcadastre.clicked.connect(self.afficheCadastre)
            self.dockwidget.Boxbdortho.clicked.connect(self.afficheBdortho)
            self.dockwidget.Boxadminexpress.clicked.connect(self.afficheAdminexpress)
            
            #Connection du lien tapé par l'utilisateur au pushbutton : 
            self.dockwidget.pushButton.clicked.connect(self.chemin)
           

            self.dockwidget.checkBoxAdministratif.clicked.connect(self.ouvAdministratif)
            self.dockwidget.checkBoxAdresse.clicked.connect(self.ouvAdresse)
            self.dockwidget.checkBoxBati.clicked.connect(self.ouvBati)
            self.dockwidget.checkBoxHydro.clicked.connect(self.ouvHydro)
            self.dockwidget.checkBoxLieuNomme.clicked.connect(self.ouvLieuNomme)
            self.dockwidget.checkBoxOccupationDuSol.clicked.connect(self.ouvOccupationDuSol)
            self.dockwidget.checkBoxServiceEtActivite.clicked.connect(self.ouvServiceEtActivite)
            self.dockwidget.checkBoxTransport.clicked.connect(self.ouvTransport)
            self.dockwidget.checkBoxZoneRegle.clicked.connect(self.ouvZonereglementee)
           
            # connect to provide cleanup on closing of dockwidget
            self.dockwidget.closingPlugin.connect(self.onClosePlugin)

            # show the dockwidget
            # TODO: fix to allow choice of dock location
            self.iface.addDockWidget(Qt.RightDockWidgetArea, self.dockwidget)
            self.dockwidget.show()
    
    #Fonction permettant de récupérer le fichier BDTopo
    def chemin(self):
        self.url = self.dockwidget.lineEdit.text()
    
    #Fonctions permattant d'aller chercher les différents flux WFS accessible sur le site de l'IGN    
    def affichePhotoAerienne(self):
        print('test')
        if self.dockwidget.Boxphoto.isChecked():
            print('deja')
            url = 'contextualWMSLegend=0&crs=EPSG:3857&dpiMode=7&featureCount=10&format=image/jpeg&'
            url = url + 'layers=ORTHOIMAGERY.ORTHOPHOTOS&styles=normal&tileMatrixSet=PM'
            wms_url = url + '&url=http://wxs.ign.fr/choisirgeoportail/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities'
            rlayer = QgsRasterLayer(wms_url, 'Photographie', 'wms')
            QgsProject.instance().addMapLayer(rlayer)
            print (rlayer)
        else:
            print('else')
            for fond in QgsProject.instance().mapLayers().values():
                if fond.name() == "Photographie":
                    rlayer = fond
            print(rlayer.name())
            QgsProject.instance().removeMapLayer(rlayer)
            self.canvas.refresh()
            
    def affichePlaniIGN(self):
        print('test')
        if self.dockwidget.Boxplani.isChecked():
            print('deja')
            url = 'contextualWMSLegend=0&crs=EPSG:3857&dpiMode=7&featureCount=10&format=image/png&'
            url = url + 'layers=GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2&styles=normal&tileMatrixSet=PM'
            wms_url = url + '&url=http://wxs.ign.fr/choisirgeoportail/geoportail/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities'
            
            
            
            blayer = QgsRasterLayer(wms_url, 'Plan IGN', 'wms')
            QgsProject.instance().addMapLayer(blayer)
            print (blayer)
        
        else:
            print('else')
            for fond in QgsProject.instance().mapLayers().values():
                if fond.name() == "Plan IGN":
                    blayer = fond
                    print(blayer.name())
            QgsProject.instance().removeMapLayer(blayer)
            self.canvas.refresh()
            
    
    def afficheCadastre(self):
        if self.dockwidget.Boxcadastre.isChecked():
            url = 'contextualWMSLegend=0&crs=EPSG:3857&dpiMode=7&featureCount=10&format=image/png&'
            url = url + 'layers=CADASTRALPARCELS.PARCELLAIRE_EXPRESS&styles=PCI%20vecteur&tileMatrixSet=PM'
            wms_url = url + '&url=http://wxs.ign.fr/choisirgeoportail/geoportail/wmts?SERVICE%3DWMTS%26VERSION%3D1.0.0%26REQUEST%3DGetCapabilities'
            
            clayer = QgsRasterLayer(wms_url, 'Cadastre', 'wms')
            QgsProject.instance().addMapLayer(clayer)
            print (clayer)
       
        
        else:
            print('else')
            for fond in QgsProject.instance().mapLayers().values():
                if fond.name() == "Cadastre":
                    clayer = fond
                    print ('cadastre')
                    print(clayer.name())
            QgsProject.instance().removeMapLayer(clayer)
            self.canvas.refresh()
            
            
    def afficheBdortho(self):
        if self.dockwidget.Boxbdortho.isChecked():
            url='crs=EPSG:3857&dpiMode=7&format=image/png&layers=ORTHOIMAGERY.ORTHOPHOTOS.BDORTHO&styles&url=https://wxs.ign.fr/choisirgeoportail/geoportail/r/wms'
            dlayer = QgsRasterLayer(url, 'Ortho50cm', 'wms')
            QgsProject.instance().addMapLayer(dlayer)
            print (dlayer)
        
        else:
            for fond in QgsProject.instance().mapLayers().values():
                if fond.name() == "Ortho50cm":
                    dlayer = fond
                    print(dlayer.name())
            QgsProject.instance().removeMapLayer(dlayer)
            self.canvas.refresh()
            
    
    def afficheAdminexpress(self):
        if self.dockwidget.Boxadminexpress.isChecked():
            url = 'crs=CRS:84&dpiMode=7&format=image/png&layers=LIMITES_ADMINISTRATIVES_EXPRESS.LATEST&styles&url=https://wxs.ign.fr/choisirgeoportail/geoportail/r/wms'
            elayer = QgsRasterLayer(url, 'Limites Administratives', 'wms')
            QgsProject.instance().addMapLayer(elayer)
            print (elayer)
        
        else:
            print('else')
            for fond in QgsProject.instance().mapLayers().values():
                if fond.name() == "Limites Administratives":
                    elayer = fond
            print(elayer.name())
            QgsProject.instance().removeMapLayer(elayer)
            self.canvas.refresh()


    def ouvAdministratif(self):
        #
        if self.dockwidget.checkBoxAdministratif.isChecked():
            #
            self.layer1_1 = QgsVectorLayer(self.url + '/ADMINISTRATIF/REGION.shp', 'Region', 'ogr')
            self.layer1_2 = QgsVectorLayer(self.url + '/ADMINISTRATIF/COLLECTIVITE_TERRITORIALE.shp', 'Collectivite territoriale', 'ogr')
            self.layer1_3 = QgsVectorLayer(self.url + '/ADMINISTRATIF/DEPARTEMENT.shp', 'Departement', 'ogr')
            self.layer1_4 = QgsVectorLayer(self.url + '/ADMINISTRATIF/ARRONDISSEMENT.shp', 'Arrondissement', 'ogr')
            self.layer1_5 = QgsVectorLayer(self.url + '/ADMINISTRATIF/EPCI.shp', 'ECPI', 'ogr')
            self.layer1_6 = QgsVectorLayer(self.url + '/ADMINISTRATIF/COMMUNE.shp', 'Commune', 'ogr')
            self.layer1_7 = QgsVectorLayer(self.url + '/ADMINISTRATIF/COMMUNE_ASSOCIEE_OU_DELEGUEE.shp', 'Commune associee', 'ogr')
            self.layer1_8 = QgsVectorLayer(self.url + '/ADMINISTRATIF/CONDOMINIUM.shp', 'Condominium', 'ogr')
            self.layer1_9 = QgsVectorLayer(self.url + '/ADMINISTRATIF/ARRONDISSEMENT_MUNICIPAL.shp', 'Arrondissement municipal', 'ogr')
            #
            self.SymboAdmi()
            #
            QgsProject.instance().addMapLayer(self.layer1_1)
            QgsProject.instance().addMapLayer(self.layer1_2)
            QgsProject.instance().addMapLayer(self.layer1_3)
            QgsProject.instance().addMapLayer(self.layer1_4)
            QgsProject.instance().addMapLayer(self.layer1_5)
            QgsProject.instance().addMapLayer(self.layer1_6)
            QgsProject.instance().addMapLayer(self.layer1_7)
            QgsProject.instance().addMapLayer(self.layer1_8)
            QgsProject.instance().addMapLayer(self.layer1_9)
             
           
        else:
            #
            QgsProject.instance().removeMapLayer(self.layer1_1)
            QgsProject.instance().removeMapLayer(self.layer1_2)
            QgsProject.instance().removeMapLayer(self.layer1_3)
            QgsProject.instance().removeMapLayer(self.layer1_4)
            QgsProject.instance().removeMapLayer(self.layer1_5)
            QgsProject.instance().removeMapLayer(self.layer1_6)
            QgsProject.instance().removeMapLayer(self.layer1_7)
            QgsProject.instance().removeMapLayer(self.layer1_8)
            QgsProject.instance().removeMapLayer(self.layer1_9)
            #
            self.canvas.refresh()
           
    def SymboAdmi(self):  
        #
        propsA = {'color': '#F6CECE', 'size':'1', 'color_border' : '0,0,0', 'width_border': '0'}
        A = QgsFillSymbol.createSimple(propsA)
        propsB = {'color': '#F5A9A9', 'size':'1', 'color_border' : '0,0,0', 'width_border': '0'}
        B = QgsFillSymbol.createSimple(propsB)
        propsC = {'color': '#F78181', 'size':'1', 'color_border' : '0,0,0', 'width_border': '0'}
        C = QgsFillSymbol.createSimple(propsC)
        propsD = {'color': '#FA5858', 'size':'1', 'color_border' : '0,0,0', 'width_border': '0'}
        D = QgsFillSymbol.createSimple(propsD)
        propsE = {'color': '#FE2E2E', 'size':'1', 'color_border' : '0,0,0', 'width_border': '0'}
        E = QgsFillSymbol.createSimple(propsE)
        propsF = {'color': '#EF3434', 'size':'1', 'color_border' : '0,0,0', 'width_border': '0'}
        F = QgsFillSymbol.createSimple(propsF)
        propsG = {'color': '#B40404', 'size':'1', 'color_border' : '0,0,0', 'width_border': '0'}
        G = QgsFillSymbol.createSimple(propsG)
#        propsH = {'color': '#B40404', 'size':'1', 'color_border' : '0,0,0', 'width_border': '0'}
#        H = QgsFillSymbol.createSimple(propsH)
#        propsI = {'color': '#B40404', 'size':'1', 'color_border' : '0,0,0', 'width_border': '0'}
#        I = QgsFillSymbol.createSimple(propsI)
        #
        self.layer1_1.setRenderer(QgsSingleSymbolRenderer(A))    
        self.layer1_2.setRenderer(QgsSingleSymbolRenderer(B))
        self.layer1_3.setRenderer(QgsSingleSymbolRenderer(C))        
        self.layer1_4.setRenderer(QgsSingleSymbolRenderer(D))        
        self.layer1_5.setRenderer(QgsSingleSymbolRenderer(E))        
        self.layer1_6.setRenderer(QgsSingleSymbolRenderer(F))        
        self.layer1_7.setRenderer(QgsSingleSymbolRenderer(G))
        self.layer1_7.setRenderer(QgsSingleSymbolRenderer(H))
        self.layer1_7.setRenderer(QgsSingleSymbolRenderer(I))
     

    def ouvAdresse(self):
        #
        if self.dockwidget.checkBoxAdresse.isChecked():
            #
            self.layer2_1 = QgsVectorLayer(self.url + "/ADRESSES/VOIE_NOMMEE.shp", 'Voie nomme', 'ogr')
            self.layer2_2 = QgsVectorLayer(self.url + "/ADRESSES/ADRESSE.shp", 'Adresse', 'ogr')
            #
            self.SymboAdresse()
            #
            QgsProject.instance().addMapLayer(self.layer2_1)
            QgsProject.instance().addMapLayer(self.layer2_2)
           
        else:
            #
            QgsProject.instance().removeMapLayer(self.layer2_1)
            QgsProject.instance().removeMapLayer(self.layer2_2)
            #
            self.canvas.refresh()

    def SymboAdresse(self):
        #
        lineA = QgsLineSymbol.createSimple({'line_style': 'continue', 'color': '#FF8000'})
        #
        self.layer2_1.renderer().setSymbol(lineA)
       
        #
        symbolB = QgsMarkerSymbol.createSimple({'name': 'circle', 'color': '#E482ED', 'color_border' : '0,0,0', 'width_border': '0,3'})
        #
        self.layer2_2.renderer().setSymbol(symbolB)            
           
    def ouvBati(self):
        #
        if self.dockwidget.checkBoxBati.isChecked() :
            #
            self.layer3_1 = QgsVectorLayer(self.url + "/BATI/BATIMENT.shp", 'Batiment ', 'ogr')            
            self.layer3_2 = QgsVectorLayer(self.url + "/BATI/CIMETIERE.shp", "Cimetière", 'ogr')          
            self.layer3_3 = QgsVectorLayer(self.url + "/BATI/RESERVOIR.shp", 'Réservoir ', 'ogr')            
            self.layer3_4 = QgsVectorLayer(self.url + "/BATI/TERRAIN_DE_SPORT.shp", 'Terrain de sport ', 'ogr')            
            self.layer3_5 = QgsVectorLayer(self.url + "/BATI/CONSTRUCTION_SURFACIQUE.shp", "Construction surfacique", 'ogr')                
            self.layer3_6 = QgsVectorLayer(self.url + "/BATI/CONSTRUCTION_LINEAIRE.shp", 'Construction Linéaire', 'ogr')            
            self.layer3_7 = QgsVectorLayer(self.url + "/BATI/LIGNE_OROGRAPHIQUE.shp", 'Ligne Orographique', 'ogr')            
            self.layer3_8 = QgsVectorLayer(self.url + "/BATI/CONSTRUCTION_PONCTUELLE.shp", 'Construction Ponctuelle', 'ogr')            
            self.layer3_9 = QgsVectorLayer(self.url + "/BATI/PYLONE.shp", 'Pylone', 'ogr')            
            self.layer3_10 = QgsVectorLayer(self.url + "/BATI/TOPONYMIE_BATI.shp", 'Toponymie bati ', 'ogr')            
            self.layer3_11 = QgsVectorLayer(self.url + "/BATI/DETAIL_HYDROGRAPHIQUE.shp", 'Détails', 'ogr')
            #
            self.SymboBati()
            #
            QgsProject.instance().addMapLayer(self.layer3_1)
            QgsProject.instance().addMapLayer(self.layer3_2)
            QgsProject.instance().addMapLayer(self.layer3_3)
            QgsProject.instance().addMapLayer(self.layer3_4)
            QgsProject.instance().addMapLayer(self.layer3_5)
            QgsProject.instance().addMapLayer(self.layer3_6)
            QgsProject.instance().addMapLayer(self.layer3_7)
            QgsProject.instance().addMapLayer(self.layer3_8)
            QgsProject.instance().addMapLayer(self.layer3_9)
            QgsProject.instance().addMapLayer(self.layer3_10)
            QgsProject.instance().addMapLayer(self.layer3_11)
           
        else:
            #
            QgsProject.instance().removeMapLayer(self.layer3_1)
            QgsProject.instance().removeMapLayer(self.layer3_2)
            QgsProject.instance().removeMapLayer(self.layer3_3)
            QgsProject.instance().removeMapLayer(self.layer3_4)
            QgsProject.instance().removeMapLayer(self.layer3_5)
            QgsProject.instance().removeMapLayer(self.layer3_6)
            QgsProject.instance().removeMapLayer(self.layer3_7)
            QgsProject.instance().removeMapLayer(self.layer3_8)
            QgsProject.instance().removeMapLayer(self.layer3_9)
            QgsProject.instance().removeMapLayer(self.layer3_10)
            QgsProject.instance().removeMapLayer(self.layer3_11)
            #
            self.canvas.refresh()
           
    def SymboBati(self):
        #
        propsA = {'color': '#8A4B08', 'size':'1', 'color_border' : '0,0,0', 'width_border': '0.3'}
        A = QgsFillSymbol.createSimple(propsA)
        propsB = {'color': '#424242', 'size':'1', 'color_border' : '0,0,0', 'width_border': '0.3'}
        B = QgsFillSymbol.createSimple(propsB)
        propsC = {'color': '#088A85', 'size':'1', 'color_border' : '0,0,0', 'width_border': '0.3'}
        C = QgsFillSymbol.createSimple(propsC)
        propsD = {'color': '#088A4B', 'size':'1', 'color_border' : '0,0,0', 'width_border': '0.3'}
        D = QgsFillSymbol.createSimple(propsD)
        propsE = {'color': '#868A08', 'size':'1', 'color_border' : '0,0,0', 'width_border': '0'}
        E = QgsFillSymbol.createSimple(propsE)
        #
        self.layer3_1.setRenderer(QgsSingleSymbolRenderer(A))        
        self.layer3_2.setRenderer(QgsSingleSymbolRenderer(B))        
        self.layer3_3.setRenderer(QgsSingleSymbolRenderer(C))        
        self.layer3_4.setRenderer(QgsSingleSymbolRenderer(D))        
        self.layer3_5.setRenderer(QgsSingleSymbolRenderer(E))
       
        #
        lineF = QgsLineSymbol.createSimple({'line_style': 'continue', 'color': '#8A0886'})
        lineG = QgsLineSymbol.createSimple({'line_style': 'continue', 'color': '#868A08'})
        #                                  
        self.layer3_6.renderer().setSymbol(lineF)        
        self.layer3_7.renderer().setSymbol(lineG)
       
        #
        symbolH = QgsMarkerSymbol.createSimple({'name': 'circle', 'color': '#FA5882', 'color_border' : '0,0,0', 'width_border': '0,3'})
        symbolI = QgsMarkerSymbol.createSimple({'name': 'circle', 'color': '#BDBDBD', 'color_border' : '0,0,0', 'width_border': '0,3'})
        symbolJ = QgsMarkerSymbol.createSimple({'name': 'circle', 'color': '#D358F7', 'color_border' : '0,0,0', 'width_border': '0,3'})
        #                                      
        self.layer3_8.renderer().setSymbol(symbolH)  
        self.layer3_9.renderer().setSymbol(symbolI)        
        self.layer3_10.renderer().setSymbol(symbolJ)
       
    def ouvHydro(self):
        #
        if self.dockwidget.checkBoxHydro.isChecked():
            #
            self.layer4_1 = QgsVectorLayer(self.url + '/HYDROGRAPHIE/BASSIN_VERSANT_TOPOGRAPHIQUE.shp', 'Bassin Versant', 'ogr')            
            self.layer4_2 = QgsVectorLayer(self.url + '/HYDROGRAPHIE/SURFACE_HYDROGRAPHIQUE.shp', "Surface hydrographique", 'ogr')          
            self.layer4_3 = QgsVectorLayer(self.url + '/HYDROGRAPHIE/PLAN_D_EAU.shp', "Plan d'eau", 'ogr')          
            self.layer4_4 = QgsVectorLayer(self.url + '/HYDROGRAPHIE/COURS_D_EAU.shp', "Courd d'eau", 'ogr')            
            self.layer4_5 = QgsVectorLayer(self.url + '/HYDROGRAPHIE/LIMITE_TERRE_MER.shp', "Limite terre/mer", 'ogr')            
            self.layer4_6 = QgsVectorLayer(self.url + '/HYDROGRAPHIE/TRONCON_HYDROGRAPHIQUE.shp', "Troncon hydrograpĥique", 'ogr')            
            self.layer4_7 = QgsVectorLayer(self.url + '/HYDROGRAPHIE/DETAIL_HYDROGRAPHIQUE.shp', "Détail hydrographique", 'ogr')            
            self.layer4_8 = QgsVectorLayer(self.url + '/HYDROGRAPHIE/NOEUD_HYDROGRAPHIQUE.shp', "Noeud hydrographique", 'ogr')
            self.layer4_9 = QgsVectorLayer(self.url + '/HYDROGRAPHIE/TOPONYMIE_HYDROGRAPHIE.shp', "Toponymie hydrographie", 'ogr')
            #
            self.SymboHydro()
            #
            QgsProject.instance().addMapLayer(self.layer4_1)
            QgsProject.instance().addMapLayer(self.layer4_2)
            QgsProject.instance().addMapLayer(self.layer4_3)
            QgsProject.instance().addMapLayer(self.layer4_4)
            QgsProject.instance().addMapLayer(self.layer4_5)
            QgsProject.instance().addMapLayer(self.layer4_6)
            QgsProject.instance().addMapLayer(self.layer4_7)
            QgsProject.instance().addMapLayer(self.layer4_8)
            QgsProject.instance().addMapLayer(self.layer4_9)
       
        else:
            #
            QgsProject.instance().removeMapLayer(self.layer4_1)
            QgsProject.instance().removeMapLayer(self.layer4_2)
            QgsProject.instance().removeMapLayer(self.layer4_3)
            QgsProject.instance().removeMapLayer(self.layer4_4)
            QgsProject.instance().removeMapLayer(self.layer4_5)
            QgsProject.instance().removeMapLayer(self.layer4_6)
            QgsProject.instance().removeMapLayer(self.layer4_7)
            QgsProject.instance().removeMapLayer(self.layer4_8)
            QgsProject.instance().removeMapLayer(self.layer4_9)
            #
            self.canvas.refresh()

    def SymboHydro(self):
        #
        propsA = {'color': '#CEF6F5', 'size':'1', 'color_border' : '0,0,0', 'width_border': '0'}
        A = QgsFillSymbol.createSimple(propsA)
        propsB = {'color': '#A9E2F3', 'size':'1', 'color_border' : '0,0,0', 'width_border': '0'}
        B = QgsFillSymbol.createSimple(propsB)
        propsC = {'color': '#2E64FE', 'size':'1', 'color_border' : '0,0,0', 'width_border': '0'}
        C = QgsFillSymbol.createSimple(propsC)
        #
        self.layer4_1.setRenderer(QgsSingleSymbolRenderer(A))        
        self.layer4_2.setRenderer(QgsSingleSymbolRenderer(B))        
        self.layer4_3.setRenderer(QgsSingleSymbolRenderer(C))
       
        #
        lineD = QgsLineSymbol.createSimple({'line_style': 'continue', 'color': '#23C3F9'})
        lineE = QgsLineSymbol.createSimple({'line_style': 'continue', 'color': '#002FFB'})
        lineF = QgsLineSymbol.createSimple({'line_style': 'continue', 'color': '#054291'})
        #                                    
        self.layer4_4.renderer().setSymbol(lineD)        
        self.layer4_5.renderer().setSymbol(lineE)        
        self.layer4_6.renderer().setSymbol(lineF)
       
        #
        symbolG = QgsMarkerSymbol.createSimple({'name': 'circle', 'color': '#DA81F5', 'color_border' : '0,0,0', 'width_border': '0,3'})
        symbolH = QgsMarkerSymbol.createSimple({'name': 'circle', 'color': '#08088A', 'color_border' : '0,0,0', 'width_border': '0,3'})
        symbolI = QgsMarkerSymbol.createSimple({'name': 'circle', 'color': '#084B8A', 'color_border' : '0,0,0', 'width_border': '0,3'})
        #                                        
        self.layer4_7.renderer().setSymbol(symbolG)        
        self.layer4_8.renderer().setSymbol(symbolH)        
        self.layer4_9.renderer().setSymbol(symbolI)


    def ouvLieuNomme(self):
        #
        if self.dockwidget.checkBoxLieuNomme.isChecked():
            #
            self.layer5_1 = QgsVectorLayer(self.url + '/LIEUX_NOMMES/ZONE_D_HABITATION.shp', "Zone d'habitation", 'ogr')
            self.layer5_2 = QgsVectorLayer(self.url + '/LIEUX_NOMMES/TOPONYMIE_LIEUX_NOMMES.shp', 'Toponyme lieux nommés', 'ogr')
            self.layer5_3 = QgsVectorLayer(self.url + '/LIEUX_NOMMES/DETAIL_OROGRAPHIQUE.shp', 'Détail orographique', 'ogr')
            self.layer5_4 = QgsVectorLayer(self.url + '/LIEUX_NOMMES/LIEU_DIT_NON_HABITE.shp', 'Lieu dit non habité', 'ogr')
            #
            self.SymboLieuNomme()
            #
            QgsProject.instance().addMapLayer(self.layer5_1)
            QgsProject.instance().addMapLayer(self.layer5_2)
            QgsProject.instance().addMapLayer(self.layer5_3)
            QgsProject.instance().addMapLayer(self.layer5_4)
           
        else:
            #
            QgsProject.instance().removeMapLayer(self.layer5_1)
            QgsProject.instance().removeMapLayer(self.layer5_2)
            QgsProject.instance().removeMapLayer(self.layer5_3)
            QgsProject.instance().removeMapLayer(self.layer5_4)
            #
            self.canvas.refresh()

    def SymboLieuNomme(self):
        #
        propsA = {'color': '#FF4000', 'size':'1', 'color_border' : '0,0,0', 'width_border': '0'}
        A = QgsFillSymbol.createSimple(propsA)
        #
        self.layer5_1.setRenderer(QgsSingleSymbolRenderer(A))
       
        #
        symbolB = QgsMarkerSymbol.createSimple({'name': 'circle', 'color': '#FFBF00', 'color_border' : '0,0,0', 'width_border': '0.3'})
        symbolC = QgsMarkerSymbol.createSimple({'name': 'circle', 'color': '#BFFF00', 'color_border' : '0,0,0', 'width_border': '0.3'})
        symbolD = QgsMarkerSymbol.createSimple({'name': 'circle', 'color': '#00FFFF', 'color_border' : '0,0,0', 'width_border': '0.3'})
        #                                        
        self.layer5_2.renderer().setSymbol(symbolB)
        self.layer5_3.renderer().setSymbol(symbolC)        
        self.layer5_4.renderer().setSymbol(symbolD)
       
       

    def ouvOccupationDuSol(self):
        #
        if self.dockwidget.checkBoxOccupationDuSol.isChecked():
            #
            self.layer6_1 = QgsVectorLayer(self.url + '/OCCUPATION_DU_SOL/ZONE_D_ESTRAN.shp', "Zonre d'estran", 'ogr')
            self.layer6_2 = QgsVectorLayer(self.url + '/OCCUPATION_DU_SOL/ZONE_DE_VEGETATION.shp', 'Zone de vegetation', 'ogr')
            #
            self.SymboSol()
            #
            QgsProject.instance().addMapLayer(self.layer6_1)
            QgsProject.instance().addMapLayer(self.layer6_2)
           
        else:
            #
            QgsProject.instance().removeMapLayer(self.layer6_1)
            QgsProject.instance().removeMapLayer(self.layer6_2)
            #
            self.canvas.refresh()

    def SymboSol(self):
        #
        propsA = {'color': '#086A87', 'size':'1', 'color_border' : '0,0,0', 'width_border': '0'}
        A = QgsFillSymbol.createSimple(propsA)
        propsB = {'color': '#298A08', 'size':'1', 'color_border' : '0,0,0', 'width_border': '0'}
        B = QgsFillSymbol.createSimple(propsB)
        #
        self.layer6_1.setRenderer(QgsSingleSymbolRenderer(A))        
        self.layer6_2.setRenderer(QgsSingleSymbolRenderer(B))


    def ouvServiceEtActivite(self):
        #
        if self.dockwidget.checkBoxServiceEtActivite.isChecked():
            #
            self.layer7_1 = QgsVectorLayer(self.url + '/SERVICES_ET_ACTIVITES/ZONE_D_ACTIVITE_OU_D_INTERET.shp', "Zone d'activité", 'ogr')
            self.layer7_2 = QgsVectorLayer(self.url + '/SERVICES_ET_ACTIVITES/POSTE_DE_TRANSFORMATION.shp', 'Poste de transformation', 'ogr')
            self.layer7_3 = QgsVectorLayer(self.url + '/SERVICES_ET_ACTIVITES/CANALISATION.shp', 'Canalisation', 'ogr')
            self.layer7_4 = QgsVectorLayer(self.url + '/SERVICES_ET_ACTIVITES/LIGNE_ELECTRIQUE.shp', 'Ligne électrique', 'ogr')
            self.layer7_5 = QgsVectorLayer(self.url + '/SERVICES_ET_ACTIVITES/ERP.shp', 'ERP', 'ogr')  
            self.layer7_6 = QgsVectorLayer(self.url + '/SERVICES_ET_ACTIVITES/TOPONYMIE_SERVICES_ET_ACTIVITES.shp', 'Toponyme service', 'ogr')                        
            #
            self.SymboServiceEtActivite()
            #
            QgsProject.instance().addMapLayer(self.layer7_1)
            QgsProject.instance().addMapLayer(self.layer7_2)
            QgsProject.instance().addMapLayer(self.layer7_3)
            QgsProject.instance().addMapLayer(self.layer7_4)
            QgsProject.instance().addMapLayer(self.layer7_5)
            QgsProject.instance().addMapLayer(self.layer7_6)
           
        else:
            #
            QgsProject.instance().removeMapLayer(self.layer7_1)
            QgsProject.instance().removeMapLayer(self.layer7_2)
            QgsProject.instance().removeMapLayer(self.layer7_3)
            QgsProject.instance().removeMapLayer(self.layer7_4)
            QgsProject.instance().removeMapLayer(self.layer7_5)
            QgsProject.instance().removeMapLayer(self.layer7_6)
            #
            self.canvas.refresh()

    def SymboServiceEtActivite(self):
        #
        propsA = {'color': '#958631', 'size':'1', 'color_border' : '0,0,0', 'width_border': '0'}
        A = QgsFillSymbol.createSimple(propsA)
        propsB = {'color': '#133A6A', 'size':'1', 'color_border' : '0,0,0', 'width_border': '0'}
        B = QgsFillSymbol.createSimple(propsB)
        #
        self.layer7_1.setRenderer(QgsSingleSymbolRenderer(A))        
        self.layer7_2.setRenderer(QgsSingleSymbolRenderer(B))
       
        #
        lineC = QgsLineSymbol.createSimple({'line_style': 'dash', 'color': '#002FFB'})
        lineD = QgsLineSymbol.createSimple({'line_style': 'continue', 'color': '#4F6988'})
        #
        self.layer7_3.renderer().setSymbol(lineC)        
        self.layer7_4.renderer().setSymbol(lineD)
       
        #
        symbolE = QgsMarkerSymbol.createSimple({'name': 'circle', 'color': '#EDB59A', 'color_border' : '0,0,0', 'width_border': '0,3'})        
        symbolF = QgsMarkerSymbol.createSimple({'name': 'circle', 'color': '#ECA713', 'color_border' : '0,0,0', 'width_border': '0,3'})
        #
        self.layer7_5.renderer().setSymbol(symbolE)                                        
        self.layer7_6.renderer().setSymbol(symbolF)

    def ouvTransport(self):
        #
        if self.dockwidget.checkBoxTransport.isChecked():
            #
            self.layer8_1 = QgsVectorLayer(self.url + '/TRANSPORT/EQUIPEMENT_DE_TRANSPORT.shp', 'Equipement de transport', 'ogr')
            self.layer8_2 = QgsVectorLayer(self.url + '/TRANSPORT/AERODROME.shp', 'Aerodrome', 'ogr')
            self.layer8_3 = QgsVectorLayer(self.url + '/TRANSPORT/PISTE_D_AERODROME.shp', 'Piste aerodrome', 'ogr')
            self.layer8_4 = QgsVectorLayer(self.url + '/TRANSPORT/TRONCON_DE_ROUTE.shp', 'Troncon de route', 'ogr')
            self.layer8_5 = QgsVectorLayer(self.url + '/TRANSPORT/VOIE_FERREE_NOMMEE.shp', 'Voie ferree nommee', 'ogr')
            self.layer8_6 = QgsVectorLayer(self.url + '/TRANSPORT/ITI_AUTRE.shp', 'ITI autre', 'ogr')
            self.layer8_7 = QgsVectorLayer(self.url + '/TRANSPORT/ROUTE_NUMEROTEE_OU_NOMMEE.shp', 'Route numerotee', 'ogr')
            self.layer8_8 = QgsVectorLayer(self.url + '/TRANSPORT/TRONCON_DE_VOIE_FERREE.shp', 'Troncon de voie ferree', 'ogr')
            self.layer8_9 = QgsVectorLayer(self.url + '/TRANSPORT/POINT_DE_REPERE.shp', 'Point de repere', 'ogr')
            self.layer8_10 = QgsVectorLayer(self.url + '/TRANSPORT/NON_COMMUNICATION.shp', 'Non communication', 'ogr')
            self.layer8_11 = QgsVectorLayer(self.url + '/TRANSPORT/POINT_DU_RESEAU.shp', 'Point du reseau', 'ogr')
            self.layer8_12 = QgsVectorLayer(self.url + '/TRANSPORT/TOPONYMIE_TRANSPORT.shp', 'Toponyme transport', 'ogr')
            #
            self.SymboTransport()
            #
            QgsProject.instance().addMapLayer(self.layer8_1)            
            QgsProject.instance().addMapLayer(self.layer8_2)
            QgsProject.instance().addMapLayer(self.layer8_3)            
            QgsProject.instance().addMapLayer(self.layer8_4)            
            QgsProject.instance().addMapLayer(self.layer8_5)          
            QgsProject.instance().addMapLayer(self.layer8_6)            
            QgsProject.instance().addMapLayer(self.layer8_7)
            QgsProject.instance().addMapLayer(self.layer8_8)            
            QgsProject.instance().addMapLayer(self.layer8_9)            
            QgsProject.instance().addMapLayer(self.layer8_10)            
            QgsProject.instance().addMapLayer(self.layer8_11)            
            QgsProject.instance().addMapLayer(self.layer8_12)
           
        else:
            #
            QgsProject.instance().removeMapLayer(self.layer8_1)
            QgsProject.instance().removeMapLayer(self.layer8_2)
            QgsProject.instance().removeMapLayer(self.layer8_3)
            QgsProject.instance().removeMapLayer(self.layer8_4)
            QgsProject.instance().removeMapLayer(self.layer8_5)
            QgsProject.instance().removeMapLayer(self.layer8_6)
            QgsProject.instance().removeMapLayer(self.layer8_7)
            QgsProject.instance().removeMapLayer(self.layer8_8)
            QgsProject.instance().removeMapLayer(self.layer8_9)
            QgsProject.instance().removeMapLayer(self.layer8_10)
            QgsProject.instance().removeMapLayer(self.layer8_11)
            QgsProject.instance().removeMapLayer(self.layer8_12)
            #
            self.canvas.refresh()
   
    def SymboTransport(self):
        #
        propsA = {'color': '#E6E6E6', 'size':'1', 'color_border' : '0,0,0', 'width_border': '0'}
        A = QgsFillSymbol.createSimple(propsA)
        propsB = {'color': '#CED8F6', 'size':'1', 'color_border' : '0,0,0', 'width_border': '0'}
        B = QgsFillSymbol.createSimple(propsB)
        propsC = {'color': '#CEECF5', 'size':'1', 'color_border' : '0,0,0', 'width_border': '0'}
        C = QgsFillSymbol.createSimple(propsC)
        #
        self.layer8_1.setRenderer(QgsSingleSymbolRenderer(A))        
        self.layer8_2.setRenderer(QgsSingleSymbolRenderer(B))
        self.layer8_3.setRenderer(QgsSingleSymbolRenderer(C))
       
        #
        lineD = QgsLineSymbol.createSimple({'line_style': 'continue', 'color': '#A4A4A4'})
        lineE = QgsLineSymbol.createSimple({'line_style': 'dash', 'color': '#000000'})
        lineF = QgsLineSymbol.createSimple({'line_style': 'continue', 'color': '#8A2908'})
        lineG = QgsLineSymbol.createSimple({'line_style': 'continue', 'color': '#DF0101'})
        lineH = QgsLineSymbol.createSimple({'line_style': 'dash', 'color': '#581C01'})
        #                                  
        self.layer8_4.renderer().setSymbol(lineD)        
        self.layer8_5.renderer().setSymbol(lineE)        
        self.layer8_6.renderer().setSymbol(lineF)
        self.layer8_7.renderer().setSymbol(lineG)        
        self.layer8_8.renderer().setSymbol(lineH)
       
        #
        symbolI = QgsMarkerSymbol.createSimple({'name': 'circle', 'color': '#F3F781', 'color_border' : '0,0,0', 'width_border': '0,3'})
        symbolJ = QgsMarkerSymbol.createSimple({'name': 'circle', 'color': '#FFBF00', 'color_border' : '0,0,0', 'width_border': '0,3'})
        symbolK = QgsMarkerSymbol.createSimple({'name': 'circle', 'color': '#F7BE81', 'color_border' : '0,0,0', 'width_border': '0,3'})
        symbolL = QgsMarkerSymbol.createSimple({'name': 'circle', 'color': '#FA5858', 'color_border' : '0,0,0', 'width_border': '0,3'})
        #                                      
        self.layer8_9.renderer().setSymbol(symbolI)        
        self.layer8_10.renderer().setSymbol(symbolJ)        
        self.layer8_11.renderer().setSymbol(symbolK)        
        self.layer8_12.renderer().setSymbol(symbolL)
   
    def ouvZonereglementee(self):
        #
        if self.dockwidget.checkBoxZoneRegle.isChecked():
            #
            self.layer9_1 = QgsVectorLayer(self.url + '/ZONES_REGLEMENTEES/FORET_PUBLIQUE.shp', 'Foret publique', 'ogr')
            self.layer9_2 = QgsVectorLayer(self.url + '/ZONES_REGLEMENTEES/PARC_OU_RESERVE.shp', 'Parc ou reserve', 'ogr')
            self.layer9_3 = QgsVectorLayer(self.url + '/ZONES_REGLEMENTEES/TOPONYMIE_ZONES_REGLEMENTEES.shp', 'Toponyme zone reglementee', 'ogr')
            #
            self.SymboZone()
            #
            QgsProject.instance().addMapLayer(self.layer9_1)
            QgsProject.instance().addMapLayer(self.layer9_2)
            QgsProject.instance().addMapLayer(self.layer9_3)
           
        else:
            #
            QgsProject.instance().removeMapLayer(self.layer9_1)
            QgsProject.instance().removeMapLayer(self.layer9_2)
            QgsProject.instance().removeMapLayer(self.layer9_3)
            #
            self.canvas.refresh()

    def SymboZone(self):
        #
        propsA = {'color': '#085B18', 'size':'1', 'color_border' : '0,0,0', 'width_border': '0'}
        A = QgsFillSymbol.createSimple(propsA)
        propsB = {'color': '#E0F8E0', 'size':'1', 'color_border' : '0,0,0', 'width_border': '0'}
        B = QgsFillSymbol.createSimple(propsB)
        #
        self.layer9_1.setRenderer(QgsSingleSymbolRenderer(A))
        self.layer9_2.setRenderer(QgsSingleSymbolRenderer(B))
       
        #
        symbolC = QgsMarkerSymbol.createSimple({'name': 'circle', 'color': '#A4A4A4', 'color_border' : '0,0,0', 'width_border': '0.3'})
        #
        self.layer9_3.renderer().setSymbol(symbolC)
    
# =============================================================================
#     def ouvAdministratif(self):
#         if self.dockwidget.checkBoxAdministratif.isChecked():
#             self.layer1_1 = QgsVectorLayer(self.url + '/ADMINISTRATIF/REGION.shp', 'Region', 'ogr')
#             QgsProject.instance().addMapLayer(self.layer1_1)
#             self.layer1_2 = QgsVectorLayer(self.url + '/ADMINISTRATIF/COLLECTIVITE_TERRITORIALE.shp', 'Collectivite territoriale', 'ogr')
#             QgsProject.instance().addMapLayer(self.layer1_2)
#             self.layer1_3 = QgsVectorLayer(self.url + '/ADMINISTRATIF/DEPARTEMENT.shp', 'Departement', 'ogr')
#             QgsProject.instance().addMapLayer(self.layer1_3)
#             self.layer1_4 = QgsVectorLayer(self.url + '/ADMINISTRATIF/ARRONDISSEMENT.shp', 'Arrondissement', 'ogr')
#             QgsProject.instance().addMapLayer(self.layer1_4)
#             self.layer1_5 = QgsVectorLayer(self.url + '/ADMINISTRATIF/EPCI.shp', 'ECPI', 'ogr')
#             QgsProject.instance().addMapLayer(self.layer1_5)
#             self.layer1_6 = QgsVectorLayer(self.url + '/ADMINISTRATIF/COMMUNE.shp', 'Commune', 'ogr')
#             QgsProject.instance().addMapLayer(self.layer1_6)
#             self.layer1_7 = QgsVectorLayer(self.url + '/ADMINISTRATIF/COMMUNE_ASSOCIEE_OU_DELEGUEE.shp', 'Commune associee', 'ogr')
#             QgsProject.instance().addMapLayer(self.layer1_7)
#              
#            
#         else:
#             QgsProject.instance().removeMapLayer(self.layer1_1)
#             QgsProject.instance().removeMapLayer(self.layer1_2)
#             QgsProject.instance().removeMapLayer(self.layer1_3)
#             QgsProject.instance().removeMapLayer(self.layer1_4)
#             QgsProject.instance().removeMapLayer(self.layer1_5)
#             QgsProject.instance().removeMapLayer(self.layer1_6)
#             QgsProject.instance().removeMapLayer(self.layer1_7)
#             self.canvas.refresh()
#            
#            
# 
#     def ouvAdresse(self):
#         if self.dockwidget.checkBoxAdresse.isChecked():
#             self.layer2_1 = QgsVectorLayer(self.url + "/ADRESSES/ADRESSE.shp", 'Adresse', 'ogr')
#             QgsProject.instance().addMapLayer(self.layer2_1)
#             self.layer2_2 = QgsVectorLayer(self.url + "/ADRESSES/VOIE_NOMMEE.shp", 'Voie nommee', 'ogr')
#             QgsProject.instance().addMapLayer(self.layer2_2)
#            
#         else:
#             QgsProject.instance().removeMapLayer(self.layer2_1)
#             QgsProject.instance().removeMapLayer(self.layer2_2)
#             self.canvas.refresh()
#            
#            
#     def ouvBati(self):
#         if self.dockwidget.checkBoxBati.isChecked() :
#             self.layer3_1 = QgsVectorLayer(self.url + "/BATI/BATIMENT.shp", 'Batiment ', 'ogr')
#             QgsProject.instance().addMapLayer(self.layer3_1)
#             self.layer3_2 = QgsVectorLayer(self.url + "/BATI/CIMETIERE.shp", "Cimetière", 'ogr')
#             QgsProject.instance().addMapLayer(self.layer3_2)    
#             self.layer3_3 = QgsVectorLayer(self.url + "/BATI/DETAIL_HYDROGRAPHIQUE.shp", 'Détails', 'ogr')
#             QgsProject.instance().addMapLayer(self.layer3_3)    
#             self.layer3_4 = QgsVectorLayer(self.url + "/BATI/CONSTRUCTION_LINEAIRE.shp", 'Construction Linéaire', 'ogr')
#             QgsProject.instance().addMapLayer(self.layer3_4)    
#             self.layer3_5 = QgsVectorLayer(self.url + "/BATI/CONSTRUCTION_PONCTUELLE.shp", 'Construction Ponctuelle', 'ogr')
#             QgsProject.instance().addMapLayer(self.layer3_5)
#             self.layer3_6 = QgsVectorLayer(self.url + "/BATI/CONSTRUCTION_SURFACIQUE.shp", "Construction surfacique", 'ogr')
#             QgsProject.instance().addMapLayer(self.layer3_6)
#             self.layer3_7 = QgsVectorLayer(self.url + "/BATI/LIGNE_OROGRAPHIQUE.shp", 'Ligne Orographique', 'ogr')
#             QgsProject.instance().addMapLayer(self.layer3_7)
#             self.layer3_8 = QgsVectorLayer(self.url + "/BATI/PYLONE.shp", 'Pylone', 'ogr')
#             QgsProject.instance().addMapLayer(self.layer3_8)
#             self.layer3_9 = QgsVectorLayer(self.url + "/BATI/RESERVOIR.shp", 'Réservoir ', 'ogr')
#             QgsProject.instance().addMapLayer(self.layer3_9)
#             self.layer3_10 = QgsVectorLayer(self.url + "/BATI/TERRAIN_DE_SPORT.shp", 'Terrain de sport ', 'ogr')
#             QgsProject.instance().addMapLayer(self.layer3_10)
#             self.layer3_11 = QgsVectorLayer(self.url + "/BATI/TOPONYMIE_BATI.shp", 'Toponymie bati ', 'ogr')
#             QgsProject.instance().addMapLayer(self.layer3_11)
#            
#         else:
#             QgsProject.instance().removeMapLayer(self.layer3_1)
#             QgsProject.instance().removeMapLayer(self.layer3_2)
#             QgsProject.instance().removeMapLayer(self.layer3_3)
#             QgsProject.instance().removeMapLayer(self.layer3_4)
#             QgsProject.instance().removeMapLayer(self.layer3_5)
#             QgsProject.instance().removeMapLayer(self.layer3_6)
#             QgsProject.instance().removeMapLayer(self.layer3_7)
#             QgsProject.instance().removeMapLayer(self.layer3_8)
#             QgsProject.instance().removeMapLayer(self.layer3_9)
#             QgsProject.instance().removeMapLayer(self.layer3_10)
#             QgsProject.instance().removeMapLayer(self.layer3_11)
#             self.canvas.refresh()
#            
#            
#     def ouvHydro(self):
#        
#         if self.dockwidget.checkBoxHydro.isChecked():
#             self.layer4_1 = QgsVectorLayer(self.url + '/HYDROGRAPHIE/BASSIN_VERSANT_TOPOGRAPHIQUE.shp', 'Bassin Versant', 'ogr')
#             QgsProject.instance().addMapLayer(self.layer4_1)
#             self.layer4_2 = QgsVectorLayer(self.url + '/HYDROGRAPHIE/COURS_D_EAU.shp', "Courd d'eau", 'ogr')
#             QgsProject.instance().addMapLayer(self.layer4_2)
#             self.layer4_3 = QgsVectorLayer(self.url + '/HYDROGRAPHIE/DETAIL_HYDROGRAPHIQUE.shp', "Détail hydrographique", 'ogr')
#             QgsProject.instance().addMapLayer(self.layer4_3)
#             self.layer4_4 = QgsVectorLayer(self.url + '/HYDROGRAPHIE/LIMITE_TERRE_MER.shp', "Limite terre/mer", 'ogr')
#             QgsProject.instance().addMapLayer(self.layer4_4)
#             self.layer4_5 = QgsVectorLayer(self.url + '/HYDROGRAPHIE/NOEUD_HYDROGRAPHIQUE.shp', "Noeud hydrographique", 'ogr')
#             QgsProject.instance().addMapLayer(self.layer4_5)
#             self.layer4_6 = QgsVectorLayer(self.url + '/HYDROGRAPHIE/PLAN_D_EAU.shp', "Plan d'eau", 'ogr')
#             QgsProject.instance().addMapLayer(self.layer4_6)
#             self.layer4_7 = QgsVectorLayer(self.url + '/HYDROGRAPHIE/SURFACE_HYDROGRAPHIQUE.shp', "Surface hydrographique", 'ogr')
#             QgsProject.instance().addMapLayer(self.layer4_7)
#             self.layer4_8 = QgsVectorLayer(self.url + '/HYDROGRAPHIE/TOPONYMIE_HYDROGRAPHIE.shp', "Toponymie hydrographie", 'ogr')
#             QgsProject.instance().addMapLayer(self.layer4_8)
#             self.layer4_9 = QgsVectorLayer(self.url + '/HYDROGRAPHIE/TRONCON_HYDROGRAPHIQUE.shp', "Troncon hydrograpĥique", 'ogr')
#             QgsProject.instance().addMapLayer(self.layer4_9)
#        
#         else:
#             print('else')
#             QgsProject.instance().removeMapLayer(self.layer4_1)
#             QgsProject.instance().removeMapLayer(self.layer4_2)
#             QgsProject.instance().removeMapLayer(self.layer4_3)
#             QgsProject.instance().removeMapLayer(self.layer4_4)
#             QgsProject.instance().removeMapLayer(self.layer4_5)
#             QgsProject.instance().removeMapLayer(self.layer4_6)
#             QgsProject.instance().removeMapLayer(self.layer4_7)
#             QgsProject.instance().removeMapLayer(self.layer4_8)
#             QgsProject.instance().removeMapLayer(self.layer4_9)
#             self.canvas.refresh()
# 
# 
# 
#     def ouvLieuNomme(self):
#         if self.dockwidget.checkBoxLieuNomme.isChecked():
#             self.layer5_1 = QgsVectorLayer(self.url + '/LIEUX_NOMMES/DETAIL_OROGRAPHIQUE.shp', 'Detail orographique', 'ogr')
#             QgsProject.instance().addMapLayer(self.layer5_1)
#             self.layer5_2 = QgsVectorLayer(self.url + '/LIEUX_NOMMES/DETAIL_OROGRAPHIQUE.shp', 'Detail orographique', 'ogr')
#             QgsProject.instance().addMapLayer(self.layer5_2)
#             self.layer5_3 = QgsVectorLayer(self.url + '/LIEUX_NOMMES/LIEU_DIT_NON_HABITE.shp', 'Lieu dit non habite', 'ogr')
#             QgsProject.instance().addMapLayer(self.layer5_3)  
#             self.layer5_4 = QgsVectorLayer(self.url + '/LIEUX_NOMMES/TOPONYMIE_LIEUX_NOMMES.shp', 'Toponyme lieux nommes', 'ogr')
#             QgsProject.instance().addMapLayer(self.layer5_4)  
#             self.layer5_5 = QgsVectorLayer(self.url + '/LIEUX_NOMMES/ZONE_D_HABITATION.shp', 'Zone d habitation', 'ogr')
#             QgsProject.instance().addMapLayer(self.layer5_5)
#            
#         else:
#             QgsProject.instance().removeMapLayer(self.layer5_1)
#             QgsProject.instance().removeMapLayer(self.layer5_2)
#             QgsProject.instance().removeMapLayer(self.layer5_3)
#             QgsProject.instance().removeMapLayer(self.layer5_4)
#             QgsProject.instance().removeMapLayer(self.layer5_5)
#             self.canvas.refresh()
# 
# 
# 
#     def ouvOccupationDuSol(self):
#         if self.dockwidget.checkBoxOccupationDuSol.isChecked():
#             self.layer6_1 = QgsVectorLayer(self.url + '/OCCUPATION_DU_SOL/ZONE_D_ESTRAN.shp', 'Zonre d estran', 'ogr')
#             QgsProject.instance().addMapLayer(self.layer6_1)
#             self.layer6_2 = QgsVectorLayer(self.url + '/OCCUPATION_DU_SOL/ZONE_DE_VEGETATION.shp', 'Zonre de vegetation', 'ogr')
#             QgsProject.instance().addMapLayer(self.layer6_2)
#            
#         else:
#             QgsProject.instance().removeMapLayer(self.layer6_1)
#             QgsProject.instance().removeMapLayer(self.layer6_2)
#             self.canvas.refresh()
# 
# 
# 
#     def ouvServiceEtActivite(self):        
#         if self.dockwidget.checkBoxServiceEtActivite.isChecked():
#             self.layer7_1 = QgsVectorLayer(self.url + '/SERVICES_ET_ACTIVITES/CANALISATION.shp', 'Canalisation', 'ogr')
#             QgsProject.instance().addMapLayer(self.layer7_1)
#             self.layer7_2 = QgsVectorLayer(self.url + '/SERVICES_ET_ACTIVITES/ERP.shp', 'ERP', 'ogr')
#             QgsProject.instance().addMapLayer(self.layer7_2)
#             self.layer7_3 = QgsVectorLayer(self.url + '/SERVICES_ET_ACTIVITES/LIGNE_ELECTRIQUE.shp', 'Ligne electrique', 'ogr')
#             QgsProject.instance().addMapLayer(self.layer7_3)
#             self.layer7_4 = QgsVectorLayer(self.url + '/SERVICES_ET_ACTIVITES/POSTE_DE_TRANSFORMATION.shp', 'Poste de transformation', 'ogr')
#             QgsProject.instance().addMapLayer(self.layer7_4)
#             self.layer7_5 = QgsVectorLayer(self.url + '/SERVICES_ET_ACTIVITES/TOPONYMIE_SERVICES_ET_ACTIVITES.shp', 'Toponyme service', 'ogr')
#             QgsProject.instance().addMapLayer(self.layer7_5)
#             self.layer7_6 = QgsVectorLayer(self.url + '/SERVICES_ET_ACTIVITES/ZONE_D_ACTIVITE_OU_D_INTERET.shp', "Zone d'activite", 'ogr')
#             QgsProject.instance().addMapLayer(self.layer7_6)
#            
#         else:
#             QgsProject.instance().removeMapLayer(self.layer7_1)
#             QgsProject.instance().removeMapLayer(self.layer7_2)
#             QgsProject.instance().removeMapLayer(self.layer7_3)
#             QgsProject.instance().removeMapLayer(self.layer7_4)
#             QgsProject.instance().removeMapLayer(self.layer7_5)
#             QgsProject.instance().removeMapLayer(self.layer7_6)
#             self.canvas.refresh()
# 
# 
# 
#     def ouvTransport(self):
#         if self.dockwidget.checkBoxTransport.isChecked():
#             self.layer8_1 = QgsVectorLayer(self.url + '/TRANSPORT/AERODROME.shp', 'Aerodrome', 'ogr')
#             QgsProject.instance().addMapLayer(self.layer8_1)
#             self.layer8_2 = QgsVectorLayer(self.url + '/TRANSPORT/EQUIPEMENT_DE_TRANSPORT.shp', 'Equipement de transport', 'ogr')
#             QgsProject.instance().addMapLayer(self.layer8_2)
#             self.layer8_3 = QgsVectorLayer(self.url + '/TRANSPORT/ITI_AUTRE.shp', 'ITI autre', 'ogr')
#             QgsProject.instance().addMapLayer(self.layer8_3)
#             self.layer8_4 = QgsVectorLayer(self.url + '/TRANSPORT/NON_COMMUNICATION.shp', 'Non communication', 'ogr')
#             QgsProject.instance().addMapLayer(self.layer8_4)
#             self.layer8_5 = QgsVectorLayer(self.url + '/TRANSPORT/PISTE_D_AERODROME.shp', 'Piste aerodrome', 'ogr')
#             QgsProject.instance().addMapLayer(self.layer8_5)
#             self.layer8_6 = QgsVectorLayer(self.url + '/TRANSPORT/POINT_DE_REPERE.shp', 'Point de repere', 'ogr')
#             QgsProject.instance().addMapLayer(self.layer8_6)
#             self.layer8_7 = QgsVectorLayer(self.url + '/TRANSPORT/POINT_DU_RESEAU.shp', 'Point du reseau', 'ogr')
#             QgsProject.instance().addMapLayer(self.layer8_7)
#             self.layer8_8 = QgsVectorLayer(self.url + '/TRANSPORT/ROUTE_NUMEROTEE_OU_NOMMEE.shp', 'Route numerotee', 'ogr')
#             QgsProject.instance().addMapLayer(self.layer8_8)
#             self.layer8_9 = QgsVectorLayer(self.url + '/TRANSPORT/TOPONYMIE_TRANSPORT.shp', 'Toponyme transport', 'ogr')
#             QgsProject.instance().addMapLayer(self.layer8_9)
#             self.layer8_10 = QgsVectorLayer(self.url + '/TRANSPORT/TRONCON_DE_ROUTE.shp', 'Troncon de route', 'ogr')
#             QgsProject.instance().addMapLayer(self.layer8_10)
#             self.layer8_11 = QgsVectorLayer(self.url + '/TRANSPORT/TRONCON_DE_VOIE_FERREE.shp', 'Troncon de voie ferree', 'ogr')
#             QgsProject.instance().addMapLayer(self.layer8_11)
#             self.layer8_12 = QgsVectorLayer(self.url + '/TRANSPORT/VOIE_FERREE_NOMMEE.shp', 'Voie ferree nommee', 'ogr')
#             QgsProject.instance().addMapLayer(self.layer8_12)
#            
#         else:
#             QgsProject.instance().removeMapLayer(self.layer8_1)
#             QgsProject.instance().removeMapLayer(self.layer8_2)
#             QgsProject.instance().removeMapLayer(self.layer8_3)
#             QgsProject.instance().removeMapLayer(self.layer8_4)
#             QgsProject.instance().removeMapLayer(self.layer8_5)
#             QgsProject.instance().removeMapLayer(self.layer8_6)
#             QgsProject.instance().removeMapLayer(self.layer8_7)
#             QgsProject.instance().removeMapLayer(self.layer8_8)
#             QgsProject.instance().removeMapLayer(self.layer8_9)
#             QgsProject.instance().removeMapLayer(self.layer8_10)
#             QgsProject.instance().removeMapLayer(self.layer8_11)
#             QgsProject.instance().removeMapLayer(self.layer8_12)
#             self.canvas.refresh()
#    
#    
#    
#     def ouvZonereglementee(self):
#         if self.dockwidget.checkBoxZoneRegle.isChecked():
#             self.layer9_1 = QgsVectorLayer(self.url + '/ZONES_REGLEMENTEES/FORET_PUBLIQUE.shp', 'Foret publique', 'ogr')
#             QgsProject.instance().addMapLayer(self.layer9_1)      
#             self.layer9_2 = QgsVectorLayer(self.url + '/ZONES_REGLEMENTEES/PARC_OU_RESERVE.shp', 'Parc ou reserve', 'ogr')
#             QgsProject.instance().addMapLayer(self.layer9_2)      
#             self.layer9_3 = QgsVectorLayer(self.url + '/ZONES_REGLEMENTEES/TOPONYMIE_ZONES_REGLEMENTEES.shp', 'Toponyme zone reglementee', 'ogr')
#             QgsProject.instance().addMapLayer(self.layer9_3)
#        
#         else:
#             QgsProject.instance().removeMapLayer(self.layer9_1)
#             QgsProject.instance().removeMapLayer(self.layer9_2)
#             QgsProject.instance().removeMapLayer(self.layer9_3)
#             self.canvas.refresh()
# =============================================================================
